
package soap.ws.botuser;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BotUserService", targetNamespace = "http://botuser.ws.soap/", wsdlLocation = "https://buss-chernukha.herokuapp.com/botuser?wsdl")
public class BotUserService
    extends Service
{

    private final static URL BOTUSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOTUSERSERVICE_EXCEPTION;
    private final static QName BOTUSERSERVICE_QNAME = new QName("http://botuser.ws.soap/", "BotUserService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://buss-chernukha.herokuapp.com/botuser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOTUSERSERVICE_WSDL_LOCATION = url;
        BOTUSERSERVICE_EXCEPTION = e;
    }

    public BotUserService() {
        super(__getWsdlLocation(), BOTUSERSERVICE_QNAME);
    }

    public BotUserService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOTUSERSERVICE_QNAME, features);
    }

    public BotUserService(URL wsdlLocation) {
        super(wsdlLocation, BOTUSERSERVICE_QNAME);
    }

    public BotUserService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOTUSERSERVICE_QNAME, features);
    }

    public BotUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BotUserService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBotUserService
     */
    @WebEndpoint(name = "BotUserServiceImplPort")
    public IBotUserService getBotUserServiceImplPort() {
        return super.getPort(new QName("http://botuser.ws.soap/", "BotUserServiceImplPort"), IBotUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBotUserService
     */
    @WebEndpoint(name = "BotUserServiceImplPort")
    public IBotUserService getBotUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://botuser.ws.soap/", "BotUserServiceImplPort"), IBotUserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOTUSERSERVICE_EXCEPTION!= null) {
            throw BOTUSERSERVICE_EXCEPTION;
        }
        return BOTUSERSERVICE_WSDL_LOCATION;
    }

}
