
package soap.ws.skiresortitem;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISkiResortItemService", targetNamespace = "http://skiresortitem.ws.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISkiResortItemService {


    /**
     * 
     * @param user
     * @return
     *     returns boolean
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(name = "createdSkiResortItem", targetNamespace = "")
    @RequestWrapper(localName = "createSkiResortItem", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.CreateSkiResortItem")
    @ResponseWrapper(localName = "createSkiResortItemResponse", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.CreateSkiResortItemResponse")
    @Action(input = "http://skiresortitem.ws.soap/ISkiResortItemService/createSkiResortItemRequest", output = "http://skiresortitem.ws.soap/ISkiResortItemService/createSkiResortItemResponse", fault = {
        @FaultAction(className = ApiException_Exception.class, value = "http://skiresortitem.ws.soap/ISkiResortItemService/createSkiResortItem/Fault/ApiException")
    })
    public boolean createSkiResortItem(
        @WebParam(name = "user", targetNamespace = "")
        SkiResortItem user)
        throws ApiException_Exception
    ;

    /**
     * 
     * @param itemId
     * @return
     *     returns soap.ws.skiresortitem.SkiResortItem
     */
    @WebMethod
    @WebResult(name = "skiResortItemById", targetNamespace = "")
    @RequestWrapper(localName = "getSkiResortItem", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.GetSkiResortItem")
    @ResponseWrapper(localName = "getSkiResortItemResponse", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.GetSkiResortItemResponse")
    @Action(input = "http://skiresortitem.ws.soap/ISkiResortItemService/getSkiResortItemRequest", output = "http://skiresortitem.ws.soap/ISkiResortItemService/getSkiResortItemResponse")
    public SkiResortItem getSkiResortItem(
        @WebParam(name = "itemId", targetNamespace = "")
        String itemId);

    /**
     * 
     * @param itemId
     * @param rating
     * @param userId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "createdRating", targetNamespace = "")
    @RequestWrapper(localName = "addSkiItemRating", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.AddSkiItemRating")
    @ResponseWrapper(localName = "addSkiItemRatingResponse", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.AddSkiItemRatingResponse")
    @Action(input = "http://skiresortitem.ws.soap/ISkiResortItemService/addSkiItemRatingRequest", output = "http://skiresortitem.ws.soap/ISkiResortItemService/addSkiItemRatingResponse")
    public boolean addSkiItemRating(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "itemId", targetNamespace = "")
        String itemId,
        @WebParam(name = "rating", targetNamespace = "")
        int rating);

    /**
     * 
     * @param rating
     * @param userId
     * @return
     *     returns java.util.List<soap.ws.skiresortitem.SkiResortItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEvaluatedItemsWithRating", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.GetEvaluatedItemsWithRating")
    @ResponseWrapper(localName = "getEvaluatedItemsWithRatingResponse", targetNamespace = "http://skiresortitem.ws.soap/", className = "soap.ws.skiresortitem.GetEvaluatedItemsWithRatingResponse")
    @Action(input = "http://skiresortitem.ws.soap/ISkiResortItemService/getEvaluatedItemsWithRatingRequest", output = "http://skiresortitem.ws.soap/ISkiResortItemService/getEvaluatedItemsWithRatingResponse")
    public List<SkiResortItem> getEvaluatedItemsWithRating(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "rating", targetNamespace = "")
        int rating);

}
